[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper MIME types for JavaScript modules
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"